title: Palme Tech Wiki
description: Palme Tech Wiki and Knowledge Base

url: "https://h3mul.github.io"
baseurl: ""

logo: /assets/img/palme-logo-eagle.png
favicon_ico: "/assets/img/favicons/favicon.ico"

theme: just-the-docs

aux_links:
  Palme Tech Github: https://github.com/palme-tech
  Palme Theater Home: https://palmetheatre.com

callouts:
  warning:
    color: yellow

lang: en

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Hemul
  email: phil.d324@gmail.com
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/h3mul # change to your Twitter homepage

defaults:
  - scope:
      path: "docs"
      type: pages 
    values:
      layout: wiki
      toc: true
  - scope:
      path: "docs/inventory/fixtures"
    values:
      parent: Fixture Inventory
      toc: true

analytics:
  goatcounter:
    id: palme-tech

pageviews:
  provider: goatcounter

post_date_format : "%b %e %Y at %I:%M %p"

color_scheme: dark

color_schemes:
  dark: 'dark'
  light: 'light'

remote_theme: just-the-docs/just-the-docs@v0.10.1
plugins:
  - jekyll-remote-theme
  - jekyll-last-modified-at

exclude:
  [
    "node_modules/",
    "*.gemspec",
    "*.gem",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "package-lock.json",
    "script/",
    "LICENSE.txt",
    "lib/",
    "bin/",
    "README.md",
    "Rakefile",
    "docker-compose.yaml",
  ]

sass:
  # Hide darken() dep warnings
  # https://github.com/just-the-docs/just-the-docs/issues/1541#issuecomment-2401649789
  quiet_deps: true 